apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flaskapp
  namespace: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flaskapp
  template:
    metadata:
      labels:
        app: python-flaskapp
    spec:
      containers:
        - name: python-flaskapp
          image: mitchlauren/python-flaskapp:v15-5c1a159
          ports:
            - containerPort: 5000
